### ISSUE TITLE
[develop] simple match report

### ISSUE THREAD

**Issue by saeeeeru** [saeeeeru/WyscoutAnalyzer#1]
# done
* we can check match report with summary, shot points, pass lines, and else.

# task
* [x]  build framework using streamlit
* [x]  add side bar
* [x]  add select box of match, period, library
* [x]  add figure of shot map, pass lines
* [x]  add match summary with score, number of shots, on target, number of passes, and else.
* [ ]  add figure of duel map
